name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch: 
  push: {branches: ["master", "main"]}
jobs:
  github-achievements:
    name: Compact display
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.achievements.compact.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: polyglot, stargazer, deployer, maintainer, developer, scripter, packager, explorer, infograhile
          plugin_achievements_ignored: polyglot, stargazer, deployer, maintainer, developer, scripter, packager, explorer, infograhile
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
