name: Youtube Music - Recently listed
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  Youtube-music:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.musics.svg
          token: NOT_NEEDED
          base: ""
          plugin_music_token: ${{ secrets.YOUTUBE_MUSIC_TOKEN }}
          plugin_music: yes
          plugin_music_mode: recent
          plugin_music_provider: youtube
